---
title: 'The NEMO project'
date: '2024-04-07T00:00:00'
output: 
   blogdown::html_page
---

### <ins>NE</ins>twork and pairwise meta-analysis with <ins>M</ins>issing <ins>O</ins>utcome data

::: {style="padding: 10px; margin-bottom: 10px; color: black; background-color: #EBEBEB; border-color: #EBEBEB; font-size: 25px;"}
**Project description**
:::

### The problem with missing participant outcome data in evidence synthesis

Missing (participant) outcome data are ubiquitous in systematic reviews. In the absence of individual participant outcome data, it is challenging to address missing outcome data in their aggregate format. Therefore, (aggregate) missing outcome data have preoccupied many researchers, leading to a rather abundant published literature on that special topic mainly in the pairwise meta-analysis framework. While the methodology already developed in pairwise meta-analysis can be elaborated further to operate in a network of interventions, addressing missing outcome data in network meta-analysis holds an additional degree of complexity. 

### A call for research attention to this topic

The NEMO project was initiated in 2017 as a response to the scarce publication agenda on the methodology of missing outcome data in the network meta-analysis. For instance, there was no evidence on the prevalence, reporting and handling of missing outcome data in systematic reviews with network meta-analysis. Evidence on the performance of different methods to handle missing outcome data when conducting network meta-analysis was missing as well. 

The **first phase of the NEMO project** provided empirical evidence on the reporting and handling of missing outcome data in networks of interventions, followed by a thorough empirical and simulation evaluation of the performance of different models to handle missing binary outcome data (for being the most prevalent outcome in evidence synthesis) in network meta-analysis. 

The **second phase of the NEMO project** aimed to enrich and further advance the methodology for missing outcome data in systematic reviews. The research agenda included an extensive refinement of current modelling strategies for continuous missing outcome data that will offer, in addition, the possibility to learn about the missingness mechanisms in the collected trials. Furthermore, a user-appealing graphical approach was developed to visualise the sensitivity analysis results from making different plausible scenarios about the missingness mechanism based on the pattern-mixture model. A highlight of this work package was the development of a novel index to infer if the primary analysis results wedre robust to different scenarios about the informative missingness parameter. Lastly, all functions developed during the project were bundled into the [rnmamod](https://cran.r-project.org/web/packages/rnmamod/index.html) R package that is published in CRAN. 

::: {style="padding: 10px; margin-bottom: 10px; color: black; background-color: #EBEBEB; border-color: #EBEBEB; font-size: 25px;"}
**Presentations**
:::

|  |  |
|:----------------|:------------------------------------------------------|
| 07/2021 | **42th Annual Conference of the International Society for Clinical Biostatistics (online), Lyon, France** |
|  | Quantifying the robustness of primary analysis results: a case study on missing outcome data in pairwise and network meta-analysis. [Download presentation](https://github.com/LoukiaSpin/loukiaspinweb/blob/main/content/projects/projects/nemopresentations/Spineli_ISCB2021 Lyon.pdf)|
| 09/2019 | **64. GMDS-Jahrestagung in Dortmund, 09.-11.09.2019** |
|  | Comparison of exclusion, imputation and modelling of missing binary outcome data in frequentist network meta-analysis. [Download presentation](https://github.com/LoukiaSpin/loukiaspinweb/blob/main/content/projects/projects/nemopresentations/Kalyvas & Spineli_ISCB2019 Leuven.pdf)|
| 07/2019 | **40th Annual Conference of the International Society for Clinical Biostatistics, Leuven, Belgium** |
|  | Comparison of exclusion, imputation and modelling of missing binary outcome data in frequentist network meta-analysis. |
| 03/2019 | **Heidelberger Kolloquium, Institute of Medical Biometry and Informatics, University of Heidelberg, Germany** |
|  | Missing Outcome Data in Network Meta-analysis of Healthcare Interventions: a combination of a systematic overview, empirical and simulation study – The NEMO (NEtwork meta-analysis with Missing Outcome data) project. [Download presentation](https://github.com/LoukiaSpin/loukiaspinweb/blob/main/content/projects/projects/nemopresentations/NEMO presentation_Heidelberg.pdf)|
| 09/2018 | **63. Jahrestagung der GMDS in Osnabrück, 02.-06.09.2018** |
|  | Comparison of methods to handle missing binary outcome data in network meta-analysis: an empirical study. [Download presentation](https://github.com/LoukiaSpin/loukiaspinweb/blob/main/content/projects/projects/nemopresentations/NMA-MOD empir_Presentation_Osnabrück.pdf)|
| 06/2018 | **Research Synthesis 2018 Conference in the University of Trier, Trier, Germany** |
|  | A systematic survey shows that reporting and handling of missing outcome data in networks of interventions is poor. [Download presentation](https://github.com/LoukiaSpin/loukiaspinweb/blob/main/content/projects/projects/nemopresentations/ResearchSynthesis_Spineli.pdf)|
| 03/2018 | **64. Biometrisches Kolloquium 2018 (IBS-DR), Biometrie: gelebte Vielfalt 25.-28. März 2018 an der Goethe-Universität Frankfurt** |
|  | A systematic survey shows that reporting and handling of missing outcome data in networks of interventions is poor. |

::: {style="padding: 10px; margin-bottom: 10px; color: black; background-color: #EBEBEB; border-color: #EBEBEB; font-size: 25px;"}
**Publications**
:::

### Original research

::: {style="text-align: justify"}
<font size="4">**Spineli LM**. Using network meta-analysis to predict the percentage of missing participants for a future trial. *Res Methods Med Health Sci* 2023; 4(4):140-149. [Journal](https://journals.sagepub.com/doi/full/10.1177/26320843231167502)</font>

<font size="4">**Spineli LM**. A revised framework to evaluate the consistency assumption globally in a network of interventions. *Med Decis Making* 2022; 42(5):637-648. [PubMed](https://pubmed.ncbi.nlm.nih.gov/34961377/)</font>

<font size="4">**Spineli LM**, Kalyvas C, Papadimitropoulou K. How robust are findings of pairwise and network meta-analysis in the presence of missing participant outcome data? *BMC Med* 2021; 19(1):323. [PubMed](https://pubmed.ncbi.nlm.nih.gov/34930276/)</font>

<font size="4">**Spineli LM**, Kalyvas C, Papadimitropoulou K. Quantifying the robustness of primary analysis results: A case study on missing outcome data in pairwise and network meta-analysis. *Res Synth Methods* 2021; 12(4):475-490. [PubMed](https://pubmed.ncbi.nlm.nih.gov/33543587/)</font>

<font size="4">**Spineli LM**, Papadimitropoulou K, Kalyvas C. Pattern-mixture model in network meta-analysis of binary missing outcome data: one-stage or two-stage approach? *BMC Med Res Methodol* 2021; 21(1):12. [PubMed](https://pubmed.ncbi.nlm.nih.gov/33413138/)</font>

<font size="4">**Spineli LM**, Kalyvas C, Papadimitropoulou K. Continuous(ly) missing outcome data in network meta-analysis: a one-stage pattern-mixture model approach. *Stat Methods Med Res* 2021; 30(4):958-975. [PubMed](https://pubmed.ncbi.nlm.nih.gov/33406990/)</font>

<font size="4">**Spineli LM**, Kalyvas C. Comparison of exclusion, imputation and modelling of missing binary outcome data in frequentist network meta-analysis. *BMC Med Res Methodol* 2020; 20(1):48. [PubMed](https://pubmed.ncbi.nlm.nih.gov/32111167/)</font>

<font size="4">**Spineli LM**, Kalyvas C, Pateras K. Participants’ outcomes gone missing within a network of interventions: Bayesian modeling strategies. *Stat Med* 2019; 38(20):3861-3879. [PubMed](https://pubmed.ncbi.nlm.nih.gov/31134664/)</font>

<font size="4">**Spineli LM**. An empirical comparison of Bayesian modelling strategies for missing binary outcome data in network meta-analysis. *BMC Med Res Methodol* 2019; 19(1):86. [PubMed](https://pubmed.ncbi.nlm.nih.gov/31018836/)</font>

<font size="4">**Spineli LM**, Yepes-Nuñez JJ, Schünemann HJ. A systematic survey shows that reporting and handling of missing outcome data in networks of interventions is poor. *BMC Med Res Methodol* 2018; 18(1):115. [PubMed](https://pubmed.ncbi.nlm.nih.gov/30355280/)</font>

<font size="4">**Spineli LM**. Modeling missing binary outcome data while preserving transitivity assumption yielded more credible network meta-analysis results. *J Clin Epidemiol* 2019; 105:19-26. [PubMed](https://pubmed.ncbi.nlm.nih.gov/30223064/)</font>
:::

### R package

::: {style="text-align: justify"}
<font size="4">**Spineli LM**. Rnmamod: Bayesian Network Meta-Analysis with Missing Participants. R package version 0.4.0. 2024. <https://CRAN.R-project.org/package=rnmamod> [creator and maintainer]. GitHub development version in <https://github.com/LoukiaSpin/rnmamod></font>
:::
