---
title: "How it all started"
date: '2022-09-06T21:13:14-05:00'
output: 
  blogdown::html_page
---

I have aspired to study archaeology since my early teens. I excelled in history, philosophy and Latin and got good grades in Ancient Greek. It is needless to say that Ross Geller was my favourite character from the Friends TV series for being a palaeontologist, though I am more like Chandler Bing in many aspects. I ended up studying statistics. The journey theme was initial self-doubt and ‘what the heck I was thinking’ on repeat mode, followed by zero regrets and many surprises. I got some hints that statistics would be my calling during my Bachelor's studies at the University of Piraeus (Department of Statistics and Insurance Science). By the end of my studies, I was determined to pursue a Master's degree in Biostatistics, which I did at the same University and Department. Afterwards, with the encouragement of my Master's supervisor, because the self-doubt emerged once again, I moved to Ioannina to pursue my PhD Studies at the School of Medicine (Department of Hygiene and Epidemiology). Little did I know that this step would be the springboard for my career as a researcher and more surprises to follow. 

During my PhD studies, I was introduced to evidence synthesis, particularly the network meta-analysis framework. My research revolved around aggregate missing participant outcome data in network meta-analysis. Publications, international collaborations, journal clubs and presentations in conferences filled my experience canvas with unprecedented colours and set the foundation for my next big step: my relocation to Germany as a postdoctoral researcher. Of course, self-doubt relocated with me there. And, yes, ‘what the heck I was thinking’ was the initial theme on repeat mode, again. My postdoctoral experience started at the Hannover Medical School (Institute for Biostatistics). For the next three years, I contributed to statistical consultations with clinicians and medical students from the University (mostly observational studies) and the [ASTERIX project](http://www.asterix-fp7.eu/), my first international consortium. 

During the third year of my employment, [Habilitation](https://en.wikipedia.org/wiki/Habilitation) got to my attention thanks to the [Ina-Pichlmayr-Mentoring postdoctoral programme](https://www.mhh.de/gleichstellung/ina-pichlmayr-mentoring) for women. So, the plan was to fund my position at the Hannover Medical School to gain eligibility for the Habilitation process. I ventured an attempt and submitted my first funding proposal to the [German Research Foundation](https://www.dfg.de/en/). Behold! The [NEMO project](https://gepris.dfg.de/gepris/projekt/339420617?language=en) (short for **NE**twork and pairwise meta-analysis with **M**issing participant **O**utcome data). Thanks to a two-year extension of my project, I was eligible to apply for the title of [Privatdozentin](https://en.wikipedia.org/wiki/Privatdozent).

I am currently a Privatdozentin and principal investigator of the [TRACE-NMA project](https://gepris.dfg.de/gepris/projekt/462260733) (short for **TRA**nsitivity and **C**onsistency **E**valuation in **N**etwork **M**eta-**A**nalysis) in the [Midwifery Research and Education Unit of Hannover Medical School](https://www.mhh.de/hebammenwissenschaft). 
